# https://github.com/linuxserver/docker-wireguard/issues/106
version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wgvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVERURL=ddnsipdnsname.com
      - SERVERPORT=51820
      - PEERS=6
      - PEERDNS=192.168.86.1  # try with Pihole container IP. Join Bridge nw
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
    volumes:
        - /usr/src:/usr/src
        - /lib/modules:/lib/modules
        - './opt-wg:/config'
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    